package com.github.dwursteisen.libgdx.gradle

import com.github.dwursteisen.libgdx.gradle.internal.AndroidPlugin
import com.github.dwursteisen.libgdx.gradle.internal.CorePlugin
import com.github.dwursteisen.libgdx.gradle.internal.DesktopPlugin
import com.github.dwursteisen.libgdx.gradle.internal.NopPlugin
import com.github.dwursteisen.libgdx.gradle.internal.RootProjectPlugin
import com.github.dwursteisen.libgdx.gradle.internal.tryFindAssetsDirectory
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.slf4j.Logger
import org.slf4j.LoggerFactory

class LibGDXPlugin : Plugin<Project> {

    private val logger: Logger = LoggerFactory.getLogger(LibGDXPlugin::class.java)

    override fun apply(project: Project) {
        val exts = project.extensions.create("libgdx", LibGDXExtensions::class.java)
        exts.assetsDirectory = exts.assetsDirectory ?: project.tryFindAssetsDirectory()

        if (project.subprojects.isEmpty()) {
            bootstrapProjects(project)
        }
        project.subprojects.forEach {
            when (it.name) {
                "core" -> CorePlugin(exts)
                "desktop" -> DesktopPlugin(exts)
                "android" -> AndroidPlugin(exts)
                else -> NopPlugin()
            }.apply(it)
        }

        RootProjectPlugin().apply(project)
    }

    private fun bootstrapProjects(project: Project) {
        logger.info("No subprojects detected. Will bootstrap the project.")

        project.mkdir("core/src/main/kotlin")
        project.mkdir("desktop/src/main/kotlin")

        val settings = """
            // -- generated by libgdx-addons plugin -- //
            include("core", "desktop")
            """.trimIndent()

        val settingsGroovy = project.file("settings.gradle")
        if (settingsGroovy.exists()) {
            settingsGroovy.appendText(settings)
            logger.warn("Your settings.gradle was just updated. Please reload your project from your IDE.")
        }

        val settingsKotlin = project.file("settings.gradle.kts")
        if (settingsKotlin.exists()) {
            settingsKotlin.appendText(settings)
            logger.warn("Your settings.gradle.kts was just updated. Please reload your project from your IDE.")
        }
    }
}
